export const SCREEN_MEDIUM = 1270;
export const SCREEN_SMALL = 770;

export const LAPTOP_POINTS_QUANTITY = 6;
export const TABLET_POINTS_QUANTITY = 4;
export const MOBILE_POINTS_QUANTITY = 3;

export const LAPTOP_MORE_POINTS_QUANTITY = 3;
export const TABLET_MORE_POINTS_QUANTITY = 2;
export const MOBILE_MORE_POINTS_QUANTITY = 2;
